version: "3.8"

services:
  db:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile_mysql
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env_mysql
    volumes:
      # - type: volume
      #   source: mysql-data
      #   target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d
volumes:
  mysql-data:
    name: mysql-volume
